### ISSUE TITLE
App close from no were

### ISSUE THREAD

**Issue by coccco28** [jahirfiquitiva/Blueprint#106]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ] I have verified that I am using the latest version.

### Device/App info:
 - Blueprint Version: `1.2.5`
 - Android version: `8.0.0`
 - Device Manufacturer: `Samsung`
 - Device Name: `Galaxy s8+`

### Describe the bug
after update the blueprint to the lates version and try to pen the app it just close after a few seconds but on 1.2.3 is just fine

### Reproduction Steps
1.
2.
3.

### Code and/or Logs

```kotlin
println("Hello, world!")
```

```Gradle
java.lang.RuntimeException: This is an example Exception log
    at com.package.name.HelloWorld
    at com.package.name.HelloWorld$ThisIsNotARealLog
    at android.app.Instrumentation.callActivityOnResume(Instrumentation.kt)
```

**Comment by jahirfiquitiva** [comment]
Hello ... Please add some logs because otherwise I won't be able to know what is causing the issue
