### ISSUE TITLE
Card Background and Material Drawer

### ISSUE THREAD

**Issue by Axinen** [jahirfiquitiva/Blueprint#11]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ] I have verified that I am using the latest version of Blueprint.

###### Device/dashboard info:
 - Blueprint version: `1.0.6`
 - Device OS version: `7.1.2`
 - Device Manufacturer: `Google`
 - Device Name: `Nexus 6p`

Card Background color not working.
And also is possible to add material_drawer in colors.xml?

**Comment by jahirfiquitiva** [comment]
Fixed in v `1.0.7`
