### ISSUE TITLE
Feature request: Apply theme / icons button on the first page? 

### ISSUE THREAD

**Issue by jamesharvey2** [jahirfiquitiva/Blueprint#113]
Hi,

I think this project is great but this blueprint app doesn't display 'Apply Icons' button on its first page.
Believe it or not, that's not very user friendly. 
People download this kind of app just to apply icons... not to appreciate the app too much.
Is it possible for you guys to implement a big '**Apply Theme**' button on the very first page of this app? 
That's what users want to see when they download theme package. 
Otherwise people will be confused because all of its bottom menu items don't have any texts.

Thanks,

**Comment by jahirfiquitiva** [comment]
The feature is already implemented, you just need to have a supported launcher set as your default launcher for the button to appear.

**Comment by jahirfiquitiva** [comment]
Even the README shows a screenshot of this feature working.

Also, next time, please use one of the provided issue templates

**Comment by jamesharvey2** [comment]
Thanks for your response.
I see the icons, wallpaper. 

But what I meant is.. can we see very explicit 'Apply Theme' button texts like this? 
![1](https://user-images.githubusercontent.com/34139438/43238826-d99a550e-905d-11e8-9b76-8c5bb80b8aa2.png)


and can we have menu texts at the bottom so people can read menu texts before tapping? 

I think that will be much better.

**Comment by jamesharvey2** [comment]
Right now, I feel the app needs a little study for users to fully understand.

**Comment by jahirfiquitiva** [comment]
Thanks for the suggestions. This is something we'd need to think with the design team. I won't compromise saying I'd implement these suggestions right away, but we are certainly going to give it a thought.

**Comment by jamesharvey2** [comment]
Thanks for your consideration! I hope this happens. 
This is what I felt when I downloaded an icon package built on blueprint. It has good animations and look but it takes a little time to fully understand. I hope it works out of box with just 'Apply Theme!' text button which does what it says. 

Keep up the good works!

**Comment by jahirfiquitiva** [comment]
You can also use the NavigationDrawer instead of BottomNavigation and you'll have the issue with sections titles solved
