### ISSUE TITLE
Add intent for wallpaper chooser

### ISSUE THREAD

**Issue by SLCMotor** [jahirfiquitiva/Blueprint#114]
<intent-filter>
                <action android:name="android.intent.action.SET_WALLPAPER" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>

### Is your feature request related to a problem? Please describe.
Add intent for wallpaper chooser from Launcher Home screens

### Describe the solution you'd like
Added to the source. 

### Describe alternatives you've considered
manually adding myself.

### Additional context
I was asked to post here so you would not forget.

**Comment by jahirfiquitiva** [comment]
Pleass update your issue to use the issue template
