### ISSUE TITLE
Launcher not installed dialog not showing after click on launcher icon

### ISSUE THREAD

**Issue by rahul3183** [jahirfiquitiva/Blueprint#115]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version.

### Device/App info:
 - Blueprint Version: `1.2.6`
 - Android version: `8.0`
 - Device Manufacturer: `MI`
 - Device Name: `A1`

### Describe the bug
When i am clicking on the non installed launcher icon, it is not showing the popup to install from Google play store.

**Comment by jahirfiquitiva** [comment]
Please add more details to your issue. Like steps to reproduce, logs and any info about modifications you could have done to the dashboard.

**Comment by rahul3183** [comment]
I didn't did any modification. I just download the project and tried to run it.
The app is working correctly in blueprint 1.2.4 but now it's not working.

**Comment by jahirfiquitiva** [comment]
Ok. Thanks for the info. I will try to check it
