### ISSUE TITLE
Calculation of total icon number is wrong

### ISSUE THREAD

**Issue by dashlabsdeveloper** [jahirfiquitiva/Blueprint#12]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Blueprint.

###### Device/dashboard info:
 - Blueprint version: `1.0.6`
 - Device OS version: `8.1`
 - Device: `Pixel Emulator`

I attached screenshots from the sample app, there are a total number of 12 icons, on the home sektion, however, a number of 8 is displayed.

![screenshot_1518184740](https://user-images.githubusercontent.com/31287077/36031052-d4ef0c70-0da9-11e8-8691-58844610a6f5.png)
![screenshot_1518184742](https://user-images.githubusercontent.com/31287077/36031053-d5085806-0da9-11e8-81bc-b4962eee8354.png)

**Comment by jahirfiquitiva** [comment]
Fixed in v `1.0.7`
