### ISSUE TITLE
Max apps to request limit not working properly

### ISSUE THREAD

**Issue by Primokorn** [jahirfiquitiva/Blueprint#121]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version.

### Device/App info:
 - Blueprint Version: `1.2.8`
 - Android version: `8.1.0`
 - Device Manufacturer: `OnePlus`
 - Device Name: `OnePlus 3T`

### Describe the bug
Icon request limit set into `blueprint_configs.xml` can be easily bypassed without clearing app data.

### Reproduction Steps
1. For the example, let's say we have 15 icons which are not supported
2. In `blueprint_configs.xml` we set this limit:
`    <integer name="max_apps_to_request">10</integer>`
`    <integer name="time_limit_in_minutes">30240</integer>`
3. Go to the icon request screen and try to request the 15 icons. The dashboard will tell you that you can only ask 10 icons. Send the email with these 10 icons.
4. Close the app then return to the icon request tool. You will be able to send a new email with the 5 remaining icons.
Usually the limit can only be bypassed by clearing app data so it's easy to explain to our users that they are not allowed to do that. However it's harder to explain if the user has followed the steps above.

### Expected behavior
The user should only be able to ask for 10 icons and he has to wait for 30240 minutes (21 days) to see the counter reset.

### Additional context
As discussed in your G+ community: https://plus.google.com/+H%C3%A9denOS/posts/R5RwQQHo5mg

Thank you.

**Comment by jahirfiquitiva** [comment]
Should be fixed in v `1.3.0`
