### ISSUE TITLE
Sample download link doesn't work

### ISSUE THREAD

**Issue by ugurarici** [jahirfiquitiva/Blueprint#129]
Tried to download sample from this url: http://www.jahirfiquitiva.me/gh-releases/blueprint

But browser says "Couldn't find server" so I couldn't download it.

**Comment by jahirfiquitiva** [comment]
Change the `.me` in the url to `.com`

**Comment by jahirfiquitiva** [comment]
PS: Thanks for letting me know @ugurarici ... Will update the links soon
