### ISSUE TITLE
How to enable legacy navigation drawer?

### ISSUE THREAD

**Issue by dashlabsdeveloper** [jahirfiquitiva/Blueprint#13]
In Read Me navigation drawer is shown, how can I enable it?

**Comment by jahirfiquitiva** [comment]
Go to `app/src/main/kotlin/your/package/name/MainActivity.kt`

And almost at the top, I left a little comment explaining that.

😀

**Comment by dashlabsdeveloper** [comment]
Thanks, found it. Maybe you should add it to the wiki too.
