### ISSUE TITLE
Multiple iconpack apks working simultaneously

### ISSUE THREAD

**Issue by th2050** [jahirfiquitiva/Blueprint#133]
### Is your feature request related to a problem? Please describe.
I'm always frustrated when I have to think a lot between balancing the number of icons and size of the app

### Describe the solution you'd like
An icon pack which complements the earlier icon pack .i.e. multi-apk based icon pack. With this, I can create basic icons in one apk and additional icons in another apk (but more than one icon packs working at the same time). This will enable for smaller downloads by users.

### Describe alternatives you've considered
There is no alternative apart from generating a single big sized apk

**Comment by abbastafakh** [comment]
It's good idea for alt icons but how it's gonna work with switching between 2 apk??

**Comment by jahirfiquitiva** [comment]
This requires launchers support first.
