### ISSUE TITLE
请问怎么让图标包支持小米POCO桌面，谢谢

### ISSUE THREAD

**Issue by qigeco** [jahirfiquitiva/Blueprint#134]
请问怎么让图标包支持小米POCO桌面，谢谢

**Comment by jahirfiquitiva** [comment]
@qigeco Please update your issue with the required issue template, and make it in English, or I will close it.

**Comment by qigeco** [comment]
Hello, I've built 2 icon packs based on Candy bar library, they perfectly works on the majority of the launchers except Poco Launcher (ported on NON-MIUI phones).
Icon packs are correctly shown in the list of available icon packs to be installed (so I assume that Poco Launcher rscognizes the icon packs) but when applying them, icons are not applied.
I suppose there should be some code or tags to be added, or updated, but I can't figure out which ones.

Can you please share with me this info?
Please note that I've found out other icon packs based on CandyBar that actually work with Poco Launcher, so I'm sure that a solution exists, just need to know which one.

Thank you for letting this project to be real, and for the wonderful job done.

**Comment by jahirfiquitiva** [comment]
@qigeco 
Unfortunately that's not related to the dashboard, so you'll have to contact one of those developers using Blueprint for help

**Comment by qigeco** [comment]
@jahirfiquitiva   thanks

**Comment by rahul3183** [comment]
@qigeco I have the same problem but I found the solution.
We just have to copy the Appfilter.xml and Drawable.xml Files into Assets folder.
