### ISSUE TITLE
Failed Publish an app to  Google play store

### ISSUE THREAD

**Issue by iTZQing** [jahirfiquitiva/Blueprint#136]
Hi, I'm the person responsible for releasing the "Oblatum icon pack (based on Blueprint)" to Google play. We were rejected many times during the release process. 
And the fifth time we were rejected and we thought we were ok, we appealed. Google's answer:
> Dear Alexei
Thank you for contacting the Google Play team.
Status: the application (com.oblatum. Iconpack) is not available on Google Play
During the review process, we found that your application violated the "payment" policy. You can read the payment policy page for more details.
For example, your application currently allows users to donate money using a non-google Play payment system. You can refer to the attached screenshot for more information.

[
![image](https://user-images.githubusercontent.com/5062100/50265575-3210af00-045b-11e9-9f90-c2e874380c47.png)
](url)

So… I hope there is a good solution.

**Comment by jahirfiquitiva** [comment]
Many people have published apps without any issues, so you probably made something else wrong
