### ISSUE TITLE
Mainactivity.kt problem! Unresolved reference: Build config.

### ISSUE THREAD

**Issue by safeboot** [jahirfiquitiva/Blueprint#138]
So I am getting this error when trying to run the Blueprint app I'm working on.

The error is this:
D:\somerandomdirectory\code\app\src\main\kotlin\com\safeboot\leap\MainActivity.kt: (52,20): Unresolved reference: Buildconfig.

Thank you jahirfiquitiva for making Blueprint and I hope you or someone could help me with this problem. (I'm on my phone because I have no internet on my PC sorry for weird typing.)

**Comment by jahirfiquitiva** [comment]
Hi.. Please follow the Wiki properly... Everything is explained there
