### ISSUE TITLE
Options appear twice in Drawer mode | FAB options

### ISSUE THREAD

**Issue by dashlabsdeveloper** [jahirfiquitiva/Blueprint#14]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Blueprint.

###### Device/dashboard info:
 - Blueprint version: `1.0.6`
 - Device OS version: `7.1.1`
 - Device: `Pixel Emulator`

###### Expected Result

Only in drawer

Moreover, I would abandon the FAB completely because it's not its original usecase.
Guidelines say: "A floating action button represents the primary action in an application." Sharing and rating is not the primary action of an icon pack. I would suggest to put these in the action bar menu instead.

###### Actual Result

The section with about, settings and help appears in the drawer as well as in the action bar, as shown in the screenshots

![screenshot_1518193753](https://user-images.githubusercontent.com/31287077/36038085-ebbb0764-0dbe-11e8-8b03-7c0acca5aec8.png)
![screenshot_1518193627](https://user-images.githubusercontent.com/31287077/36038086-ebd39900-0dbe-11e8-9835-9742ad143182.png)

**Comment by jahirfiquitiva** [comment]
@dashlabsdeveloper 

Please fill the issue template. It is here for a reason. Issues without it will be ignored.

**Comment by dashlabsdeveloper** [comment]
Sorry, thought it wouldn't be necessary for this specific issue.

- [x ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x ] I have verified that I am using the latest version of Blueprint.

###### Device/dashboard info:
 - Blueprint version: `1.0.6`
 - Device OS version: `7.1.1`
 - Device: `Pixel Emulator`

###### Expected Result

Only in drawer

###### Actual Result

The section with about, settings and help appears in the drawer as well as in the action bar, as shown in the screenshots

![screenshot_1518193753](https://user-images.githubusercontent.com/31287077/36038085-ebbb0764-0dbe-11e8-8b03-7c0acca5aec8.png)
![screenshot_1518193627](https://user-images.githubusercontent.com/31287077/36038086-ebd39900-0dbe-11e8-9835-9742ad143182.png)

**Comment by jahirfiquitiva** [comment]
@dashlabsdeveloper 

I have edited it for you. Please do like I did from now on.

About the issue. Thanks for the valuable feedback. I'm currently thinking on how to solve it in the best possible way.

**Comment by jahirfiquitiva** [comment]
Fixed in v `1.0.7`
