### ISSUE TITLE
How to remove widgets and wallpapers?

### ISSUE THREAD

**Issue by safeboot** [jahirfiquitiva/Blueprint#145]
Is there a way to remove widgets and wallpapers?

- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ] I have verified that I am using the latest version.

### Device/App info:
 - Blueprint Version: `1.4.1`
 - Android version: `8.0`
 - Device Manufacturer: `OnePlus`
 - Device Name: `OnePlus 3`

**Comment by jahirfiquitiva** [comment]
Yes. Remove them from `MainActivity.kt` and read the wiki
