### ISSUE TITLE
Sapphyx Launcher support

### ISSUE THREAD

**Issue by rgocal** [jahirfiquitiva/Blueprint#146]
### Is your feature request related to a problem? Please describe.

I would like to add support for Sapphyx Launcher to Blueprint. I need to know, what I need to do to help make this happen =)

### Describe the solution you'd like

I have an activity that list all available icon packs in a preview activity. When the user clicks on an icon pack, icons on the desktop will change and allow the user to preview the icons before applying them.

![photo_2019-01-20_22-12-22](https://user-images.githubusercontent.com/2482221/51487020-38eb5400-1d70-11e9-841c-bbec80b4805e.jpg)

package="com.gsd.launcher.sapphyx"

`<activity
            android:name="com.gsd.launcher.sapphyx.launcher3.CustomIconPreview"
            android:theme="@style/PreviewWorkspaceTheme"
            android:autoRemoveFromRecents="true">
            <intent-filter>
                <action android:name="com.gsd.launcher.sapphyx.launcher3.CustomIconPreview" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </activity>`

### Describe alternatives you've considered

I do not know how to properly apply an icon pack outside of my provider activity yet, so I have provided the activity that launches to preview icon packs and to apply them. The newest icon pack installed is listed first. I will be working to make a faster and easier solution in the future.

### Additional context

Sapphyx launcher has a normal launcher icon and an adaptive icon for supported devices. Not sure if this is needed info.

**Comment by jahirfiquitiva** [comment]
1. Fork the project and create a new branch for the implementation
2. Add the info for your intent in the [library's `AndroidManifest.xml` file](https://github.com/jahirfiquitiva/Blueprint/blob/master/library/src/main/AndroidManifest.xml)
3. Add a new item to the list of supported launchers, and add its respective function to launch the desired intent in [`Launchers.kt`](https://github.com/jahirfiquitiva/Blueprint/blob/master/library/src/main/kotlin/jahirfiquitiva/libs/blueprint/helpers/extensions/Launchers.kt)
4. Test as much as you need and when you think it's ready, open a pull request.
😀

**Comment by rgocal** [comment]
I will get on this soon. Thank you

**Comment by rgocal** [comment]
Jokes on you stale bot
