### ISSUE TITLE
Wrong action bar items on startup without home section

### ISSUE THREAD

**Issue by dashlabsdeveloper** [jahirfiquitiva/Blueprint#15]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Blueprint.

###### Device/dashboard info:
 - Blueprint version: `1.0.7`
 - Device OS version: `8.0`
 - Device: `Pixel Emulator`

###### Reproduction Steps

Remove Home section in MainActivity.kt -> App starts with icons section

###### Actual Result

On app startup it shows icons section but with home section action bar instead of search and filter

![screenshot_1518205611](https://user-images.githubusercontent.com/31287077/36047068-4cc33ef2-0ddb-11e8-9931-d4f45803db0c.png)

**Comment by jahirfiquitiva** [comment]
Fixed in v `1.0.8`
