### ISSUE TITLE
How to add apps icons? 

### ISSUE THREAD

**Issue by megapro17** [jahirfiquitiva/Blueprint#152]
I couldn't find in wiki answer about how to link the png to the specific app.
I tried to do this tutorial, but my launcher not seeing any icons. https://web.archive.org/web/20170922114305/http://afollestad.github.io/polar-dashboard/icons.html

**Comment by jahirfiquitiva** [comment]
That's because the wiki is about how to use this dashboard, not about how to create an icon pack.

For that, check [this article on Medium](https://blog.prototypr.io/how-to-create-an-android-icon-pack-app-ecb77811b938).
