### ISSUE TITLE
View Info for Icons in Home Page Preview

### ISSUE THREAD

**Issue by AndyL964** [jahirfiquitiva/Blueprint#157]
Hi, I would like to have a way to view info on the icon (such as its title) displayed in the Home page preview.

If possible, could a shortcut to the app page on the Play Store also be added so that if you're interested in an app, you won't need to search it up manually all the time?

**Comment by jahirfiquitiva** [comment]
Won't really work on this as it isn't really required and would only make icons load longer and stuff
