### ISSUE TITLE
1.0.7 is using primary dark in drawer 

### ISSUE THREAD

**Issue by dashlabsdeveloper** [jahirfiquitiva/Blueprint#16]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Blueprint.

###### Device/dashboard info:
 - Blueprint version: `1.0.7`
 - Device OS version: `8.0`
 - Device: `Pixel Emulator`

###### Reproduction Steps

1. v1.0.7 and change primary dark color

###### Expected Result

grey background

###### Actual Result

In v1.0.7 Blueprint is using the primary dark color as background color for selected drawer items in both light and dark theme

![screenshot_1518206954](https://user-images.githubusercontent.com/31287077/36048101-63a6f43a-0dde-11e8-933d-8bd88dcdccad.png)

**Comment by jahirfiquitiva** [comment]
Fixed in v `1.0.8`
