### ISSUE TITLE
can't modify values.xml

### ISSUE THREAD

**Issue by Noctroxis** [jahirfiquitiva/Blueprint#162]
I cant seem to change any text inside a file called values.xml? Whenever I try to change certain strings such as "About this app" I can't. I get an Android Studio error letting me know the file is not in the project? What does that mean and how can I change many of the text strings in the app? Where is this values.xml file coming from and where does it actually exist? Am I unable to make any modifications to text in this app at all?

I'm new to Android development and this template is amazing. I'm learning a lot from it, so please be precise in your answers so that a novice like me can understand your instructions :)

**Comment by jahirfiquitiva** [comment]
You are trying to edit a file that is part of the library source.

Please [read the info in the README](https://github.com/jahirfiquitiva/Blueprint#library-source)

For that, search `strings.xml` file in `values` folder and add your own strings there.

For further help (and not related to modifying the library source) you can always contact the [Telegram Group](https://t.me/JFsDashSupport)
