### ISSUE TITLE
Add a way to change wallpaper control buttons layout or change it completely to properly work in seamless mode

### ISSUE THREAD

**Issue by DanyGee** [jahirfiquitiva/Blueprint#165]
### Is your feature request related to a problem? Please describe.

Yes, it is related to a problem where wallpaper's control buttons background leaves a nasty gap between them and the bottom screen edge in seamless mode (hidden/disabled navbar)...
![photo_2019-07-17_08-02-32](https://user-images.githubusercontent.com/26818551/61351107-05ded480-a86a-11e9-849c-ce7fdd774d3b.jpg)

### Describe the solution you'd like

Changing the approach from `one background for all` to `one background for each` will solve three issues at once:
✔️ will not leave a noticeable gap
✔️ will look good regardless of the system's navbar used (opaque, semi transparent or transparent)
![Blueprint_Wallpaper_Buttons_Concept_1](https://user-images.githubusercontent.com/26818551/61351404-e72d0d80-a86a-11e9-86a7-9fdc9275a44b.jpg)

✔️ will still look good even when someday seamless mode will be detected by the app
![Blueprint_Wallpaper_Buttons_Concept_2](https://user-images.githubusercontent.com/26818551/61351409-ebf1c180-a86a-11e9-8655-3c383793ab25.jpg)

### Describe alternatives you've considered

Alternatively you could change the layout to vertical...
![Blueprint_Wallpaper_Buttons_Concept_3](https://user-images.githubusercontent.com/26818551/61351436-0035be80-a86b-11e9-8764-b89d35980a48.jpg)

Please consider 🙏

**Comment by jahirfiquitiva** [comment]
Which android version and device is this happening in?

**Comment by DanyGee** [comment]
> Which android version and device is this happening in?

8.0.0
