### ISSUE TITLE
Add info if an icon was already sent in a request

### ISSUE THREAD

**Issue by DanyGee** [jahirfiquitiva/Blueprint#166]
### Is your feature request related to a problem? Please describe.

If you sent a request, the app does not inform user about it. This often leads to multiple, duplicated icon requests sent from users, cause they don't see any feedback, that an icon was already sent in a request.
### Describe the solution you'd like

Some info that the icon was already sent in a request. A text like "Already sent" or "Sent ✔️" under the icon or beside it.

**Comment by jahirfiquitiva** [comment]
There's no real way for us to know whether someone already requested an icon or not. I will encourage you to use [Arctic Manager](https://arcticmanager.com/) which can help you fix that issue

**Comment by DanyGee** [comment]
So, you telling me it is virtually impossible to create something like Candybar Dash has implemented?
(request status under appname)
![Annotation 2019-07-18 211028](https://user-images.githubusercontent.com/26818551/61485086-9b7c8000-a9a0-11e9-9a3c-3fb3be52d1dd.png)

Or do they also use some 3rd party for this?

**Comment by jahirfiquitiva** [comment]
Do this:
1. Send an icon request
2. View your icons as "requested"
3. Delete app data and cache
4. Check the app again and view your icons as "not requested"

If we want to have an actually working service, that keeps actual track of requested and not requested icons, maybe even globally, not just in a single device, but for all users, we'd need a server app, with certain capabilities and stuff.

I'm not going to build a pseudo-solution 🤷🏻‍♂️

It is **absolutely NOT** "virtually impossible" to do the same as Candybar
I just don't see the point in doing it.

**Comment by DanyGee** [comment]
OK, that was a really good argument! :clap: 
Agreed.
