### ISSUE TITLE
Popup menu background color doesn't change

### ISSUE THREAD

**Issue by Gowsky** [jahirfiquitiva/Blueprint#17]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Blueprint.

###### Device/dashboard info:
 - Blueprint version: `1.0.7`
 - Device OS version: `7.1`
 - Device Manufacturer: `Samsung`
 - Device Name: `Galaxy S5`

 
###### Reproduction Steps

1. Change Primary/Background colors in dark theme

###### Expected Result
Popup Menu background should have changed its color to `dark_theme_background`

###### Actual Result
Popup Menu background color stays as default android's dark background color

![screenshot_20180209-214516](https://user-images.githubusercontent.com/14221573/36049450-186499be-0de3-11e8-9cc2-5c91aeefded1.png)

**Comment by jahirfiquitiva** [comment]
Fixed in v `1.0.8`
