### ISSUE TITLE
Load wallpapers from other source

### ISSUE THREAD

**Issue by lakshit1** [jahirfiquitiva/Blueprint#171]
Can I load wallpapers from other sources like [Unsplash](https://unsplash.com) in your app ?

**Comment by sarsamurmu** [comment]
You can load any Image if you get the raw link of the image. It's Simple, Open a Unsplash.com on Chrome or Any Web Browser. Long Press the Image or Right Click The Image. Then Choose Open Image in a New Tab. Then Copy the Link from Address Bar. Hope it Helps.
