### ISSUE TITLE
Change system's navbar color according to selected theme

### ISSUE THREAD

**Issue by DanyGee** [jahirfiquitiva/Blueprint#175]
### Is your feature request related to a problem? Please describe.

Yes, the problem is the application does not change the navbar color to match the selected theme. If my navbar color is white and the theme is dark it creates an unpleasant distraction.
![Screenshot_2019-08-09-08-32-58](https://user-images.githubusercontent.com/26818551/62760142-8f597f00-ba83-11e9-979d-d66278eb5da4.png)

### Describe the solution you'd like

App should change the navbar color to match the theme colors.

**Comment by jahirfiquitiva** [comment]
Blueprint and any of my dashboards set the navbar color to the same `primary_dark` color you put in the `colors.xml`

if it doesn't works, then it's a system restriction and i can't fix that
