### ISSUE TITLE
Custom Icon Names

### ISSUE THREAD

**Issue by safeboot** [jahirfiquitiva/Blueprint#179]
### Is your feature request related to a problem? Please describe.

Blueprint always changed the first character to uppercase and remove dots and it frustrates me.

### Describe the solution you'd like

Add a way to support uppercase, dots, custom titles and other characters.

### Describe alternatives you've considered

I've considered sticking with it until it gets patched.

**Comment by jahirfiquitiva** [comment]
You can use the naming conventions explained in the wiki, but that's it:
https://github.com/jahirfiquitiva/Blueprint/wiki/Setting-up-icon-pack-(Part-2)#naming-icons
