### ISSUE TITLE
Hide launcher icon option appears enabled by default in settings

### ISSUE THREAD

**Issue by Gowsky** [jahirfiquitiva/Blueprint#18]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Blueprint.

###### Device/dashboard info:
 - Blueprint version: `1.0.7`
 - Device OS version: `7.1`
 - Device Manufacturer: `Samsung`
 - Device Name: `Galaxy S5`

###### Expected Result
Hide launcher icon option disabled by default

###### Actual Result
Hide launcher icon option appears enabled by default in settings, though the launcher icon isn't hidden

![screenshot_20180209-214542](https://user-images.githubusercontent.com/14221573/36049687-0181138e-0de4-11e8-9df6-85c0695c8891.png)

**Comment by jahirfiquitiva** [comment]
Fixed in v `1.0.8`
