### ISSUE TITLE
Rounded Button's and UI element

### ISSUE THREAD

**Issue by AathifMahir** [jahirfiquitiva/Blueprint#183]
Love to see Blueprint adapts to Material UI design and also auto dark mode based on system settings.

The current UI is Super Boxy and doesn't look good with other apps.

**Comment by jahirfiquitiva** [comment]
Blueprint uses its very own material theme. You are free to use the master branch and edit the UI to match your style. Keep in mind we don't provide any kind of support when doing so, as stated in the readme.

Regarding the dark theme you can check #169
