### ISSUE TITLE
Donations fails and causes app to hang

### ISSUE THREAD

**Issue by rektdeckard** [jahirfiquitiva/Blueprint#187]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version.

### Device/App info:
 - Blueprint Version: `1.5.0`
 - Android version: `7.1.1`
 - Device Manufacturer: `Motorola`
 - Device Name: `E4`

### Describe the bug
Donations feature does not appear to be working. Selecting the **Donate** button from the overflow menu triggers an error dialog reading: 

> **Error**
> Unexpected error with code 0 occurred due to unknown reasons

If a donation is attempted a second time, a dialog reading only `Loading` appears and the app hangs indefinitely.

### Reproduction Steps
1. set `override var donationsEnabled = true` in `MainActivity.kt`
2. set `override fun getLicKey(): String? = "<MY_LICENSE_KEY>"`  in `MainActivity.kt`
3. set donation items in `frames_configs.xml`:
```XML
<string-array name="donation_items">
    <item>tea</item>
    <item>beer</item>
    <item>ferrari</item>
</string-array>
```
4. Run the app and click the **Donate** button
5. PROFIT??

### Expected behavior

Donations should work, otherwise helpful logs or an error message should appear.

### Screenshots

![Screenshot_20191024-205027](https://user-images.githubusercontent.com/26732044/67535731-f6a9c700-f6a1-11e9-8f47-5aa7061cd6c4.png)

### Code and/or Logs

```kotlin
override var donationsEnabled = true

override fun amazonInstallsEnabled(): Boolean = false
override fun checkLPF(): Boolean = true
override fun checkStores(): Boolean = true

override fun getLicKey(): String? = "MY_LICENSE_KEY_I_HAVE_CHECKED_A_HUNDRED_TIMES"
...
```

There do not seem to be any relevant logs. This is all that appears in logcat during the error:
```Gradle
W/art: Before Android 4.1, method int androidx.appcompat.widget.DropDownListView.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
W/art: Before Android 4.1, method int androidx.appcompat.widget.MenuPopupWindow$MenuDropDownListView.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
D/OpenGLRenderer: endAllActiveAnimators on 0x8a2f5b00 (MenuPopupWindow$MenuDropDownListView) with handle 0x8ad4bf60
```

### Additional context

This is not a device-specific problem. I have tried this on a Pixel 3 running Android 9.0 to same effect, and one of my users are able to donate either.

**Comment by rektdeckard** [comment]
Also, since it's not clear in the setup wiki, I assume that the `donation_items` correspond to the IDs of Managed Products set up in the developer console. Is that the case?

**Comment by jahirfiquitiva** [comment]
have you installed the app from play store before testing donations? 

yes, donation items are the ids, and no, it cannot include subscriptions (and won't be added in the future)

**Comment by rektdeckard** [comment]
Ah, understood. In that case you can close the issue. It works with Managed products but not with Subscriptions. I'd recommend adding a line in the wiki about this for clarity, especially regarding the IDs.

**Comment by rektdeckard** [comment]
However there is still the bug that occurs on re-entering the Donations dialog a second time. Whether you've completed a donation or cancelled out of it the first time, this dialog seems to hang at `Loading` forever.
