### ISSUE TITLE
Paid Icon Request

### ISSUE THREAD

**Issue by AathifMahir** [jahirfiquitiva/Blueprint#189]
Hi,

We love to see "Paid Icon Request" using IAP on Blueprint because we (Icon Pack Developer's) Earn very less and with Paid Icon Request we can earn little more for the effort we put develop new icons everyday, I know developing this feature to Blueprint takes time and we are love to donate little more for your effort.

Thanks,

**Comment by jahirfiquitiva** [comment]
I currently don't have plans of implementing such feature any time soon. Sorry
