### ISSUE TITLE
[SUGGESTION] Rearrange and switch secondary drawer items to primary

### ISSUE THREAD

**Issue by dashlabsdeveloper** [jahirfiquitiva/Blueprint#19]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Blueprint.

###### Device/dashboard info:
 - Blueprint version: `1.0.8`
 - Device OS version: `8.0`
 - Device: `Pixel Emulator`

I would suggest to make the items 'settings', 'about' and 'help' PrimaryDrawerItem instead of current SecondaryDrawerItem, as in my opinion this is much more beautiful and features a corresponding icon.
Moreover, I would rearrange the options so that settings as the most important one is on top, followed by about and help. This would fit a lot of other MD apps, that are doing so.

Current:
![screenshot_1518278523](https://user-images.githubusercontent.com/31287077/36064128-a74cb37a-0e86-11e8-8ea3-a2b490650e29.png)

Suggestion:
![screenshot_1518279543](https://user-images.githubusercontent.com/31287077/36064144-b11c764c-0e86-11e8-8756-d4dfdb3c97b8.png)

**Comment by jahirfiquitiva** [comment]
I just changed them to `PrimaryDrawerItem` but I won't change their order. Available in v `1.1.0`.
