### ISSUE TITLE
[REQUEST] Ability to name icons properly

### ISSUE THREAD

**Issue by dashlabsdeveloper** [jahirfiquitiva/Blueprint#20]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Blueprint.

###### Device/dashboard info:
 - Blueprint version: `1.0.8`
 - Device OS version: `8.0`
 - Device: `Pixel Emulator`

Current behaviour:
Name of file is taken, underscores are replaced by blank and next character is made upper-case.

Problem:
Apps like 9GAG start with a number, which isn't allowed, and usecapital letter only.
Apps like Öffi use characters, that are not allowed at all.

![screenshot_1518279690](https://user-images.githubusercontent.com/31287077/36064237-4272070a-0e88-11e8-9916-e60ecdcb53b0.png)

Solution:
Ability to name icons properly, maybe also support internationalisation, as there are 
apps like Google Keep have a different name e.g. where I live

**Comment by jahirfiquitiva** [comment]
The current approach is designed this way to ease the work.
Many people just want to put the icons and do the less possible effort/work to get their icon pack working.

Icons names are the same as the PNGs due to the reason above and I won't change this behavior because it only complicates things for both designers and me.

**Comment by dashlabsdeveloper** [comment]
The character limitation is a direct consequence that names come from an array with the file names. Giving file names and names displayed separately would solve that, not sure how difficult it would be to implement that though.
I even thought about writing a script or something where everything important is put in, so ComponentInfo, file name and display name. Because this is the task most annoying to put the icon pack information in the corresponding files like icon_pack.xml, appfilter.xml or appmap.xml whereas the stuff itself is nearly the same. My coding skills are not enough for that, I'm afraid.

**Comment by jahirfiquitiva** [comment]
@dashlabsdeveloper 

Yeah, as I told you it would just increase the work for designers, having to define the name of the icon and the name of the file.

Sorry, but I won't change the current behavior. You're honestly the first (and probably the only) one to be concerned about the icon names in the app
