### ISSUE TITLE
Bug in the generation of home screen icons

### ISSUE THREAD

**Issue by pxflow** [jahirfiquitiva/Blueprint#203]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version.

### Device/App info:
 - Android version: `10`
 - Device Manufacturer: `Xiaomi`
 - Device Name: `Mi A2`

### Describe the bug
Home screen icons are not generated correctly after clicking

### Reproduction Steps
1. Open Blueprint v 2.0.3
2. Click on home screen icons

### Screenshots

![ezgif-7-fbcd0401aaea](https://user-images.githubusercontent.com/39531151/80237512-393d6380-8633-11ea-8963-45d5f6ef5439.gif)

**Comment by jahirfiquitiva** [comment]
I don't understand what's the issue

Why do you think they are not generated correctly?

**Comment by jahirfiquitiva** [comment]
@pxflow  🤔❓

**Comment by jahirfiquitiva** [comment]
Nevermind, just got it

**Comment by pxflow** [comment]
The icons preview not being clickable after giving permissions has been fixed.
However, a similar problem still exists in v 2.0.4.
When clicking on the icon preview, only 8 icons are generated, but there are 15 icons in the "icon_preview" and they are not displayed.

**Comment by jahirfiquitiva** [comment]
it is generated properly. the icons are randomized every time you click and the app will pick only the ones it needs. rotate your device to view more icons

that's really not an issue

**Comment by pxflow** [comment]
See the video I made.
The icon preview is repeated, causing a loop with a sequence of icons.
The icons are not being generated randomly, only 8 icons are generated and are in a loop.
In version 2.0.1, it was working perfectly
![ezgif-3-9b96ff2520ee](https://user-images.githubusercontent.com/39531151/80267627-62341780-8678-11ea-9917-3ca57cab9743.gif)

**Comment by jahirfiquitiva** [comment]
Fixed already... Will update soon
