### ISSUE TITLE
Changing info Cards Colors on Homescreen

### ISSUE THREAD

**Issue by Max-Patchs** [jahirfiquitiva/Blueprint#21]
![screenshot_1518360695](https://user-images.githubusercontent.com/25152124/36074679-3ee7351e-0f4c-11e8-94ae-3316750f357f.png)

how can we change the colors of these cards they don't get changed

**Comment by Gowsky** [comment]
Please fill out the issue template properly and don't ask questions.

**Comment by jahirfiquitiva** [comment]
Please fill the issue template properly
