### ISSUE TITLE
Add support for multiple icons for same identifier

### ISSUE THREAD

**Issue by juanillo62gm** [jahirfiquitiva/Blueprint#212]
I'm the developer of LightBoard XS and DarkBoard XS for iOS. With theme engine that the use on iOS we can define multiple App Icons for same icon identifier.
I don't know if that is posible with Blueprint.
Here is the example:

This is the pack selector
![2020-05-08 06 46 31](https://user-images.githubusercontent.com/12599130/81371271-b539b000-90f7-11ea-9820-7119613754b6.jpg)

Only enabled 00 Original Gradient
![2020-05-08 06 46 36](https://user-images.githubusercontent.com/12599130/81371310-d0a4bb00-90f7-11ea-8291-bdf7c3177aa3.jpg)

Only enabled 01 Original White
![2020-05-08 06 46 34](https://user-images.githubusercontent.com/12599130/81371315-d3071500-90f7-11ea-8e84-2d32e9281eec.jpg)

Only enabled 02 Original Glyphs
![2020-05-08 06 46 37](https://user-images.githubusercontent.com/12599130/81371339-e1553100-90f7-11ea-9469-61798adffe2c.jpg)

This is the example of one identifier and multiple app icons
![2020-05-08 06 46 39](https://user-images.githubusercontent.com/12599130/81371351-e87c3f00-90f7-11ea-93fd-4208ab331ee3.jpg)

I was thinking about how to implement this on Android, I have blueprint working flawlessly on a closed beta with 00 Original Gradient.
Solution 1:  Made 3 individual apps for all of them... This is too much work.
Solution 2:  I thing if people have to change every app icon from 00 Original Gradient to 01 Original White, one by one, it's a bit messy.

I hope you can help me :)

**Comment by jahirfiquitiva** [comment]
Unfortunately this is not possible. Just a limitation with how icon packs work on Android

Solution 1 and 2 are the only options I can think of, and I'm glad you already thought of them
