### ISSUE TITLE
Adding links causes issues with links as well as home screen icons walls button display

### ISSUE THREAD

**Issue by gseth** [jahirfiquitiva/Blueprint#215]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version.

### Device/App info:
 - Kuper Version: `not using`
 - Android version: `10`
 - Device Manufacturer: `one plus`
 - Device Name: `7t pro`

### Describe the bug
in home setup when you add more than 2 links, the first link double shows. this only happens when you add a google play store link. 

Now when you add even the standard two links which is not google play store link the walls and icons tab disappear.

You go to icons and come back they reappear.

One google play link and one non google play link works fine.

When you add one google play link and 2 links or more, 2 links duplicate.. After closing and reopening for say 50 times, it appears correctly, then when you close and re-open back to the same issue.

Issue was not there in v1.5. only present in current version.

### Reproduction Steps
With 2 Non google links:

1.Edit home setup with 2 non google play links
2.open app
3.go to icons
4. come back to app

One google Play Link and two non google play link:
1.Edit home setup with 1 google play link and 2 or more non google play links
2.open app

### Expected behavior
Same as it was in v1.5. Some people may not have google play link. will cause issue to put a basic support email link.

### Screenshots
With 2 Non google links:

![Screenshot_1589310633](https://user-images.githubusercontent.com/6172927/81735684-0a3c4400-94b3-11ea-8c33-8deb96925561.png)
![Screenshot_1589310640](https://user-images.githubusercontent.com/6172927/81735697-0d373480-94b3-11ea-8b1c-7e3db108ad64.png)

One google Play Link and two or more non google play link:
![Screenshot_1589311780](https://user-images.githubusercontent.com/6172927/81737026-19bc8c80-94b5-11ea-92e4-3952aaf6778d.png)

One google Play Link and one non google link (all working as intended)

![Screenshot_1589316322](https://user-images.githubusercontent.com/6172927/81743706-b97f1800-94bf-11ea-81ab-010f00fbcd5a.png)

### Additional context

For each testing different format was used, meaning play and non play links. to exactly figure out what is happening when as posted in screenshot.

Current format is what was been used from v.15 and added manually to latest version.

    
    <string-array name="home_list_titles">
        <item>MyWallApp</item>
        <item>Support</item>
        <item>Community and Support</item>
    </string-array>
    <string-array name="home_list_descriptions">
        <item>by artist for you (ads free)</item>
        <item>Get support via email</item>
        <item>Join Discord Community for Discussion and Support</item>
    </string-array>
    <string-array name="home_list_icons">
        <item>ic_mywallapp</item>
        <item>ic_email</item>
        <item>ic_discord</item>
    </string-array>
    <string-array name="home_list_links">
        <item>https://play.google.com/store/apps/details?id=com.esethnet.mywallapp</item>
        <item>mailto:mail@gseth.com?Subject=Ruggon Support</item>
        <item>https://discord.gg/xzmrs6K</item>
    </string-array>

**Comment by jahirfiquitiva** [comment]
Please add examples of the links you used when it fails

**Comment by gseth** [comment]
Links like website, mailto.

This is v1.5

![Screenshot_20200513-030253](https://user-images.githubusercontent.com/6172927/81747885-82603500-94c6-11ea-8787-9ab35ca8d8d9.jpg)

Link 1: website
Link 2: mailto like <a href="mailto:someone@example.com">
Link 3: website

**Comment by jahirfiquitiva** [comment]
@gseth Please add them as you did in the xml. Copy and paste the xml content, please

**Comment by gseth** [comment]
> @gseth Please add them as you did in the xml. Copy and paste the xml content, please

Updated main post posted in additional content.

**Comment by jahirfiquitiva** [comment]
@gseth Please add them with this format (the one you should be using)
```xml
    <!-- These arrays are for the list of apps or links in main section. -->
    <string-array name="home_list_titles">
        <item>IconShowcase</item>
        <item>An App</item>
    </string-array>
    <string-array name="home_list_descriptions">
        <item>It is the old version of this awesome dashboard</item>
        <item>This is an app</item>
    </string-array>
    <string-array name="home_list_icons">
        <item>ic_na_launcher</item>
        <item>ic_na_launcher</item>
    </string-array>
    <string-array name="home_list_links">
        <item>https://github.com/jahirfiquitiva/Blueprint</item>
        <item>https://play.google.com/store/apps/details?id=com.android.settings</item>
    </string-array>
```

**Comment by gseth** [comment]
> @gseth Please add them with this format (the one you should be using)
> 
> ```
>     
>     <string-array name="home_list_titles">
>         <item>IconShowcase</item>
>         <item>An App</item>
>     </string-array>
>     <string-array name="home_list_descriptions">
>         <item>It is the old version of this awesome dashboard</item>
>         <item>This is an app</item>
>     </string-array>
>     <string-array name="home_list_icons">
>         <item>ic_na_launcher</item>
>         <item>ic_na_launcher</item>
>     </string-array>
>     <string-array name="home_list_links">
>         <item>https://github.com/jahirfiquitiva/Blueprint</item>
>         <item>https://play.google.com/store/apps/details?id=com.android.settings</item>
>     </string-array>
> ```

Please check updated post whenever you have time and let me know if its proper and sufficient. If you want strings for each screenshot scenario given can provide that as well just have to change links.

**Comment by jahirfiquitiva** [comment]
that should suffice
thanks
