### ISSUE TITLE
Ordering filters list

### ISSUE THREAD

**Issue by Max-Patchs** [jahirfiquitiva/Blueprint#22]
![captusssre](https://user-images.githubusercontent.com/25152124/36074692-6365914c-0f4c-11e8-97f2-ee7c748ccd58.PNG)

how can we order these filters i tried in icon pack xml and it didn't work also it seems they are ordered by alphabet

**Comment by jahirfiquitiva** [comment]
Please fill the issue template properly

**Comment by Gowsky** [comment]
Please use default issue form, or your issue will be ignored.

**Comment by Max-Patchs** [comment]
oh sorry no problem
