### ISSUE TITLE
Icon request client filter

### ISSUE THREAD

**Issue by pxflow** [jahirfiquitiva/Blueprint#221]
- [ y] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ y] I have verified that I am using the latest version.

### Describe the bug
After clicking on the icon request button, there is not only the email application, but also many other ways to share the icon request.

Users may not know what to do next with the icon request.

Could you add a filter so that only email applications are displayed?

### Screenshots

![screenshot](https://user-images.githubusercontent.com/39531151/82732744-8de10680-9ce5-11ea-8b22-a04259f302a2.png)

**Comment by jahirfiquitiva** [comment]
The app already shows only email clients in stock android, I can't make it work with OEM modified android systems, sorry
