### ISSUE TITLE
Back button behavior in drawer navigation and also in Bottom navigation.

### ISSUE THREAD

**Issue by SUSANTA151** [jahirfiquitiva/Blueprint#222]
### Is your feature request related to a problem? Please describe.

The behavior of the back button when using the drawer navigation in the old blueprint dashboard is that if I'm in a different tab it takes me to the home tab. After that press the back button again, it closes the app. But in the new Blueprint dashboard, pressing the back button once closes the app immediately.

[Old Blueprint Video ](https://youtu.be/FDq5NL2_3Gw)
[New Blueprint Video ](https://youtu.be/Zcc6ndlSeS0)
### Describe the solution you'd like

While pressing the back button, the app should take me to the home tab and press again to exit the app. ( Both Drawer navigation and In Bottom Navigation )

**Comment by jahirfiquitiva** [comment]
Fixed in v `2.1.0`
