### ISSUE TITLE
The icons disappear

### ISSUE THREAD

**Issue by pxflow** [jahirfiquitiva/Blueprint#225]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version.

### Describe the bug
Icons are disappearing in version 2.1.1 and 2.1.0

### Screenshots

![ezgif-6-79ebfe74cba9](https://user-images.githubusercontent.com/39531151/84100590-983c1980-a9e2-11ea-9885-235b1423b72f.gif)

**Comment by jahirfiquitiva** [comment]
Should be fixed in v `2.1.2`
