### ISSUE TITLE
Add default file name for app bundles

### ISSUE THREAD

**Issue by sarsamurmu** [jahirfiquitiva/Blueprint#228]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version.

### Device/App info:
 - Blueprint Version: `2.1.2`

### Describe the bug
So basically, when you generate an app bundle, Android Studio generates the app bundle with `app-release.aab` as the file name. It should name the bundle in this format - `<appId>-<versionName>-<variantName>`. You can fix it easily by adding the following code to `app/build.gradle`
```gradle
...
android {
  ...
  defaultConfig {
    ...
    setArchivesBaseName("THE_NAME");
    ...
  }
  ...
}
...
```

**Comment by jahirfiquitiva** [comment]
Are you able/willing to make a PR for this? 😀

**Comment by jahirfiquitiva** [comment]
alright, no worries... I'll see what I can do in my free time
