### ISSUE TITLE
App list is not showing on home page.

### ISSUE THREAD

**Issue by shahid111111** [jahirfiquitiva/Blueprint#229]
![image](https://user-images.githubusercontent.com/35474252/85737666-35a28780-b71d-11ea-912b-002b4ef0aeea.png)

![image](https://user-images.githubusercontent.com/35474252/85738160-6edaf780-b71d-11ea-87c1-d1278e672048.png)

- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version.

### Device/App info:
 - Blueprint Version: `2.1.2`
 - Device Manufacturer: `android emulator`
 - Device Name: `Pixel 3a XL API 25`

### Describe the bug
I have added the app list in home_setup.xml but the home page is not showing any app list , the amount of items are same in all 4 arrays also i rebuild the project but the issue didn't solved...
blueprint version is 2.1.2 and i am testing it on android emulator "Pixel 3a XL API 25"

home_setup.xml >

<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:tools="http://schemas.android.com/tools" tools:ignore="MissingDefaultResource">
    
    <integer name="home_actions_style">1</integer>

    
    <bool name="show_overview">true</bool>

    
    <bool name="show_quick_apply_text">false</bool>

    
    <string name="quick_apply_custom_text"></string>

    
    <string-array name="home_list_titles">
        <item>Love these icons?</item>
        <item>Cards icon pack</item>
        <item>Color line icon pack</item>
        <item>Color line dark icon pack</item>
        <item>Twitter</item>
        <item>Instagram</item>

    </string-array>

    <string-array name="home_list_descriptions">
        <item>Support us with your rating and review.</item>
        <item>The most unique icon pack available on play store</item>
        <item>White icons with colorful outlines</item>
        <item>Dark icons with colorful outlines</item>
        <item>follow us on Twitter</item>
        <item>follow us on Instagram</item>
    </string-array>

    <string-array name="home_list_icons">
        <item>my_chart</item>
        <item>cards_iconpack_icon</item>
        <item>color_line_icon</item>
        <item>color_line_dark_icon</item>
        <item>twitter</item>
        <item>instagram</item>

    </string-array>

    <string-array name="home_list_links">
        <item></item>
        <item>https://play.google.com/store/apps/details?id=cards.icon.pack</item>
        <item>https://play.google.com/store/apps/details?id=color.line.iconpack</item>
        <item>https://play.google.com/store/apps/details?id=color.line.dark</item>
        <item>https://twitter.com/SK_wallpapers_</item>
        <item>https://www.instagram.com/_sk_wallpapers/</item>
    </string-array>
</resources>

**Comment by jahirfiquitiva** [comment]
Please update filling the issue template properly

**Comment by shahid111111** [comment]
the issue is updated properly.

**Comment by jahirfiquitiva** [comment]
@shahid111111 mind adding your home items configuration? (as code so I can use it to test)

**Comment by shahid111111** [comment]
added the home_setup.xml code.

**Comment by jahirfiquitiva** [comment]
I think the issue comes with the first item which is missing a link

**Comment by shahid111111** [comment]
it worked! thank you, but in the previous version it was working with the empty item also... anyways thanx again.

**Comment by jahirfiquitiva** [comment]
sure
