### ISSUE TITLE
Lags & Stutters while browsing icons

### ISSUE THREAD

**Issue by Duke0404** [jahirfiquitiva/Blueprint#231]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version.

### App info:
 - Blueprint Version: `2.1.2`

### Describe the bug
Jarring lags and stutters while browsing the "Icons" section of the dashboard.

### Reproduction Steps
1. Make/Choose an Adaptive Icon pack with gradient Android Vector Drawables
2. Browse "Icons" section

### Expected behavior
Smooth scrolling / no stutters.

### Screenshots
https://github.com/Duke0404/Duke0404.github.io/raw/master/ScreenRecord-20200712-214736.mp4

### Additional context
The issue appears on only one of my icon packs https://rebrand.ly/Galica I assume it's because of the gradient Drawable backgrounds. The issue does not appear on the Candybar dashboard so I assume it's not my pack's fault.

**Comment by AathifMahir** [comment]
I have verified that this issue happens with gradient drawables.

**Comment by AathifMahir** [comment]
After some testing, This issue happens after changing the adaptive icon shapes from default system shape to different one.

**Comment by Duke0404** [comment]
Is there any possibility or plan to get this issue resolved?
