### ISSUE TITLE
Sending an icon request without a valid Arctic backend API key is succeeding.

### ISSUE THREAD

**Issue by SUSANTA151** [jahirfiquitiva/Blueprint#246]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

- [x] I have verified that I am using the latest version.

### Device/App info:
 - Blueprint Version: `2.1.2`
 - Android version: `8.0.`
 - Device Manufacturer: `Motorola`
 - Device Name: `Moto Z Play`

### Describe the bug
In the blueprint_setup.xml file, when I fill any random key ( anything ) for the "arctic_backend_api_key" and build the project and then trying to send an icon request and it gets succeeded.

### Reproduction Steps
1.Fill any thing like this for Arctic API key`<string name="arctic_backend_api_key" translatable="false">hjuyt45l-huy78</string>`
2.Build the project and run the app
3.Try sending an icon request

### Expected behavior

There should be an error message.

**Comment by jahirfiquitiva** [comment]
Unfortunately there's no way for me to check if it's a valid api key or not ... maybe @justinkruit could make the service return some kind of error?

**Comment by justinkruit** [comment]
Hmm, would have expected it to return an error tbh. I could look into it some time, but in my opinion it's no priority.

**Comment by jahirfiquitiva** [comment]
@justinkruit sure thing, it isn't in mine either 👌
