### ISSUE TITLE
Individual Icons not being applied

### ISSUE THREAD

**Issue by sreeragag7** [jahirfiquitiva/Blueprint#247]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version.

### Device/App info:
 - Blueprint Version: `2.1.2`
 - Android version: `10`
 - Device Manufacturer: `OnePlus`
 - Device Name: `OnePlus 7 Pro`

### Describe the bug
When changing individual icons by going into the icon pack, it does not get applied

### Reproduction Steps
1. Long press the icon to change and go into the icon pack
2. Select the Icon

### Expected behavior

The Icon which is selected from the pack should be applied

### Screenshots

https://raw.githubusercontent.com/sreeragag7/Wallpapers/master/video_2020-10-22_10-39-51.mp4

### Code and/or Logs
<!--
Please wrap code with correct syntax highlighting. You can remove it if you think it isn't necessary.

```kotlin
println("Hello, world!")
```

If you are getting an error in the LogCat, paste here the stack trace.
Please wrap logs with Gradle syntax highlighting (it makes them look better).

```Gradle
java.lang.RuntimeException: This is an example Exception log
    at com.package.name.HelloWorld
    at com.package.name.HelloWorld$ThisIsNotARealLog
    at android.app.Instrumentation.callActivityOnResume(Instrumentation.kt)
```-->

### Additional context
<!-- Add any other context about the problem here. -->

**Comment by jahirfiquitiva** [comment]
Which launcher are you testing this in?

**Comment by sreeragag7** [comment]
> Which launcher are you testing this in?

Nova Launcher

**Comment by sreeragag7** [comment]
Fixed it. Few of icons were 512×512 and those were the ones causing the issues. Lowering it fixed the issue

**Comment by jahirfiquitiva** [comment]
that's great 😀
