### ISSUE TITLE
About donations

### ISSUE THREAD

**Issue by coccco28** [jahirfiquitiva/Blueprint#25]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ] I have verified that I am using the latest version of Blueprint.

###### Device/dashboard info:
 - Blueprint version: `1.1.0`
 - Device OS version: `8.0 oreo`
 - Device Manufacturer: `?`
 - Device Name: `samsung`
 
###### Reproduction Steps

1. donations doesn't show on the tab menu from the app theme

###### Expected Result
i will like to have that option added again into the app theme

**Comment by jahirfiquitiva** [comment]
Fixed in v `1.1.1`
