### ISSUE TITLE
Icon mask function feature

### ISSUE THREAD

**Issue by pxflow** [jahirfiquitiva/Blueprint#250]
Would it be possible to add an option to enable and disable icon mask?

Ex: A function that allows adding or removing lines

iconback img1="iconback"
iconmask img1="iconmask"
scale factor="1.0"

In the appfilter.xml file

With some launchers, you can enable and disable icon mask.

Many Stock OnePlus launcher users have requested this option because the OnePlus launcher and other launchers do not have the option to disable icon masking.

Some don't like their icons without a theme being cut with the icon mask, but others like. It would be interesting if it were possible to add this option to Blueprint.

**Comment by jahirfiquitiva** [comment]
Unfortunately such feature is not possible due to how Android apps work, it's basically a limitation of the Android system

**Comment by pxflow** [comment]
Thank you for your quick answer

I did a quick test here and there is no need to remove the lines from the appfilter.xml file

Just hide or rename the files (iconback.png) and (iconmask.png), the launcher cannot identify them and this option is disabled by default.

If there was a way that would allow users to enable or disable this option, it would be really cool.

**Comment by jahirfiquitiva** [comment]
That's still not possible
