### ISSUE TITLE
Add Microsoft Launcher support

### ISSUE THREAD

**Issue by NotWoods** [jahirfiquitiva/Blueprint#254]
### Is your feature request related to a problem? Please describe.
I'd like to use my icon pack with Microsoft Launcher. Currently, the pack appears but doesn't show any icons.

### Describe the solution you'd like
Full support for selecting icons from the pack inside Microsoft Launcher. 

### Describe alternatives you've considered
Tell people to use other launchers

**Comment by jahirfiquitiva** [comment]
Direct apply is not possible. You can still apply icon packs from the launcher settings
