### ISSUE TITLE
(may be a bug) Dashboard shows higher version than current latest release – shouldn't be possible

### ISSUE THREAD

**Issue by Martin5001** [jahirfiquitiva/Blueprint#255]
The version of Blueprint shown in its settings is higher than current latest release. It shows Blueprint 3.4.0, which, to my knowledge, doesn't exist (is not listed among GitHub releases). (And I know there are two version strings – the one for Blueprint and another for the pack – and I'm talking about the Blueprint version here.)

Maybe this is caused by the icon pack developer, however if that's the case I think it should be made so it wouldn't be possible for them to change this Blueprint version information. (Or there should be a way to tell it's some sort of custom build so we would know that the version info changed by the icon pack maker is irrelevant.)

**Comment by jahirfiquitiva** [comment]
Please use the right issue template
