### ISSUE TITLE
Icon Shapes Zoom in Previews Does Not Match Device Zoom

### ISSUE THREAD

**Issue by bkazoo** [jahirfiquitiva/Blueprint#258]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version.

### Device/App info:
 - Blueprint Version: `2.1.6`
 - Android version: `10`
 - Device Manufacturer: `Nokia`
 - Device Name: `7 plus`

### Describe the bug
In adaptive icons, selecting an Icon Shape other than 'Set by System' applies a mask that does not respect the real icon sizes in the preview.
For example, if the **device** is using circle shape for the icons, **Blueprint** 'Set by System' icon shape will show a circle with the exact same size/zoom for the adaptive icons in the icons preview. Setting **Blueprint** to 'Circle' shape will make the foreground a little bit smaller (showing more of it) and not match the expected sizes.

I have reproduced this issue in several devices. All adaptive shapes other than 'Set by System' are a little bit off.

### Reproduction Steps
1. Using an icon pack that has adaptive icons, select 'Set by System' icon shape in Blueprint. For the screenshots, a 108dp\*108dp icon with a 72dp\*72dp gray square and red background is used.
2. Change the icon shape to that shape, but instead of 'Set by System', select the actual shape. For example, if the system shape is a circle, select 'Circle' as icon shape.
3. Compare icons preview.

### Expected behavior
The icons size/zoom should match the ones from the system and the Android sizes, like those described here: https://medium.com/google-design/designing-adaptive-icons-515af294c783

### Screenshots

Red should not be shown in any shape:
![Capture](https://user-images.githubusercontent.com/4998824/106353392-83eabb00-62ea-11eb-99a5-d46e760b2423.PNG)

'Set by System' shape in Blueprint (OK):
![system](https://user-images.githubusercontent.com/4998824/106353462-04a9b700-62eb-11eb-8b58-8a3b4e3151c1.jpg)

'Circle' shape in Blueprint:
![circle](https://user-images.githubusercontent.com/4998824/106353465-05dae400-62eb-11eb-85f8-ab048bc3a913.jpg)

'Square' shape in Blueprint:
![square](https://user-images.githubusercontent.com/4998824/106353463-05424d80-62eb-11eb-9af3-b826a44b90a4.jpg)

**Comment by sarsamurmu** [comment]
The problem has been fixed in `AdaptiveIconBitmap` version `1.0.0`.
