### ISSUE TITLE
Donations being refunded after 3 days

### ISSUE THREAD

**Issue by RandleP** [jahirfiquitiva/Blueprint#261]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version.

### Device/App info:
 - Blueprint Version: `2.1.6`
 - Android version: ``
 - Device Manufacturer: ``
 - Device Name: ``

### Describe the bug
Donations being refunded after 3 days (10% refunds lately)
Refund not initiated by me and not by the user (received an email why he got a refund)

### Expected behavior
Acknowledge all purchases within three days. Perhaps a library update? 

### Additional context
Wrote an email to Google about donations being refunded automatically after 3 days.
Got the following reply: 

> Hi,
> 
> Thanks for your patience.
> 
> If you use the Google Play Billing Library version 2.0 or newer, you must acknowledge all purchases within three days. Failure to properly acknowledge purchases results in those purchases being refunded. 
> 
> Google Play supports purchasing products from inside of your app (in-app) or outside of your app (out-of-app). In order for Google Play to ensure a consistent purchase experience regardless of where the user purchases your product, you must acknowledge all purchases that have a "Success" state received through the Google Play Billing Library as soon as possible after granting entitlement to the user. If you do not acknowledge a purchase within three days, the user automatically receives a refund, and Google Play revokes the purchase. For pending transactions, the three-day window does not apply when the purchase is in a "Pending" state. Instead, it starts when the purchase has moved to the "Success" state.
> 
> Here are some specific resources on the Android Developers site:
> 
>     Acknowledge a purchase (https://developer.android.com/google/play/billing/billing_library_overview#acknowledge)
>     Google Play Billing Library 2.0 Release notes (https://developer.android.com/google/play/billing/billing_library_releases_notes#release-2_0)
>     Google Play Billing Library 3: https://developer.android.com/google/play/billing/release-notes
>     Purchases must be acknowledged within three days (https://developer.android.com/google/play/billing/billing_library_releases_notes#2_0_acknowledge)
>     API guides (http://developer.android.com/guide/index.html)
>     Android Studio & SDK (http://developer.android.com/sdk/index.html)
> 
> Also, you can find Developer Support communities listed here: http://developer.android.com/support.html
> 
> If you have other questions about using the Google Play Console, please let me know and I’ll be happy to help.
> Regards,
> L
> Google Play Developer Support

**Comment by jahirfiquitiva** [comment]
this shouldn't happen with latest versions
