### ISSUE TITLE
Language code not supported by Google

### ISSUE THREAD

**Issue by pxflow** [jahirfiquitiva/Blueprint#269]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version.

### Device/App info:
 - Blueprint Version: `2.1.8`

### Describe the bug
After updating to the latest version of Blueprint (2.1.8), I am getting this error on the Play Console.

I am using the sample version, so I cannot manually delete the folder containing this language file.

### Screenshots

![unknown](https://user-images.githubusercontent.com/39531151/115468268-399e1980-a209-11eb-8e61-b491e90adfbb.png)

**Comment by pxflow** [comment]
Are there any temporary fix that I can apply manually, until the next Blueprint update with full fix?

**Comment by jahirfiquitiva** [comment]
@pxflow in the discord server, someone has shared some info about that, feel free to join if you haven't and check that out

**Comment by pxflow** [comment]
Ok, thanks
