### ISSUE TITLE
Wallpaper apply toast message doesn't respect dark theme

### ISSUE THREAD

**Issue by Martin5001** [jahirfiquitiva/Blueprint#270]
The message shown when/after applying wallpaper doesn't respect set theme (is always light).
![Screenshot_20210506-201920_Reev Pro](https://user-images.githubusercontent.com/35201200/117347063-e08ce180-aea8-11eb-962b-122ee7c7f06b.jpg)

Blueprint 2.1.8
Android 9.0
Samsung Galaxy J7

**Comment by jahirfiquitiva** [comment]
This is made on purpose. Dark snackbars are shown in light theme. Light snackbars are shown in dark theme. It's as per material design guidelines.

Here you can see a quick preview of each theme, and change the colors to anything you'd like
https://dashbud.dev/setup

**Comment by jahirfiquitiva** [comment]
Additionally, please make sure to use one of the issue templates next time
