### ISSUE TITLE
"Files not found" error while requesting icons.

### ISSUE THREAD

**Issue by DanyGee** [jahirfiquitiva/Blueprint#271]
- [X] I have verified there are no duplicate active or recent bugs, questions, or requests
- [X] I have verified that I am using the latest version.

### Device/App info:
 - Blueprint Version: `2.2.2`
 - Android version: `10`
 - Device Manufacturer: `OnePlus`
 - Device Name: `OnePlus 5`

### Describe the bug
While creating an icon request dashboard spits an error:
![photo_2021-05-06_22-46-33](https://user-images.githubusercontent.com/26818551/117364084-c27dac00-aebd-11eb-8559-01e4c352a89d.jpg)

### Reproduction Steps
1. Open the app
2. Click on Request at the bottom bar
3. Select some apps from the list
4. Click on the Request Icons button at the bottom
5. The error message shows up

### Expected behavior

App should create a request and ask how to send it.

### Screenshots

![photo_2021-05-06_22-46-33](https://user-images.githubusercontent.com/26818551/117364830-afb7a700-aebe-11eb-8ac6-c0c09adccc0f.jpg)

### Code and/or Logs

```Gradle
05-06 21:26:19.422  9385  9738 D ViewRootImpl[MainActivity]: windowFocusChanged hasFocus=false inTouchMode=true
05-06 21:26:19.433  9385  9385 E Blueprint: Request ERROR
05-06 21:26:19.433  4829  5473 D MainServiceImplHandler: : handleMessage msg.what = 1002
```
Logfile 📦 
[logcat.txt](https://github.com/jahirfiquitiva/Blueprint/files/6437640/logcat.txt)

**Comment by PrinceAbid** [comment]
i was facing the same error, i changed the time of icon request to '0' and icons per request to 'n' and it worked, if my icon request time and icons per request is both '0' this error show up, and if the request time is not exceeded this error shows up 
i hope this was helpful,

error - 
    <integer name="max_apps_to_request">0</integer>
    <integer name="time_limit_in_minutes">0</integer>

no error - 
    <integer name="max_apps_to_request">10</integer>
    <integer name="time_limit_in_minutes">0</integer>

**Comment by PrinceAbid** [comment]
same error occurring again.

**Comment by jahirfiquitiva** [comment]
@PrinceAbid

can you add more info, like device info and/or logs?

**Comment by PrinceAbid** [comment]
thank you
