### ISSUE TITLE
SplashScreen theme not changing

### ISSUE THREAD

**Issue by SUSANTA151** [jahirfiquitiva/Blueprint#276]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version.

### Device/App info:
 - Blueprint Version: `2.2.3`
 - Android version: `8.0`
 - Device Manufacturer: `Motorola`
 - Device Name: `Moto Z Play`

### Describe the bug
I want to change my app's splash screen theme to always dark so I change `MyApp.SplashScreen` to `Frames.SplashScreen.Amoled` and run the app. But the app splash screen still white. it's not changing.

### Expected behavior
When set to `Frames.SplashScreen.Amoled` splash screen should always use dark theme.

**Comment by jahirfiquitiva** [comment]
it will always follow the system theme... you will have to enable dark theme system wide to make it dark
you can switch between Light+Dark and Light+Amoled though
in app/src/main/res/values/styles.xml line 15
