### ISSUE TITLE
Moving feedback option to main 3dot menu

### ISSUE THREAD

**Issue by ba6ul** [jahirfiquitiva/Blueprint#280]
### Blueprint Version

2.2.4

### Describe the feature

If any app changes its logo as youtube studio did, people can inform you! and also apps like amazon have 100 different apps for 100 countries and if the icon is not loading for some countries, they can let you know direct and quickly.

**Comment by jahirfiquitiva** [comment]
after further consideration, that's exactly what icon requests are for. therefore I am not doing these changes.
