### ISSUE TITLE
Can not determine path to tools.jar 

### ISSUE THREAD

**Issue by Technologx** [jahirfiquitiva/Blueprint#282]
### Requirements

- [X] I have verified there are no duplicate active or recent bugs, questions, or requests

### Blueprint Version

2.2.4

### Android Version

11

### Device Manufacturer

OnePlus

### Device Name

Nord N10 5G

### What happened?

I'm running into this issue `Cannot determine path to 'tools.jar' library for Android API 32 Platform (C:/Users/techn/AppData/Local/Android/Sdk)` . I've searched all over Google and tried everything I was able to find and still run into the issue.

### Reproduction Steps

I just did a fresh install of Android Studio and did the default settings/setup and changed some colors and package name/app name. Tried to build the signed apk and ran into the issue.

### Expected behavior

I expect it to actually generate the apk.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/17693282/146738156-6f11cc62-fae3-47e6-9ab3-5d332f7fa073.png)

### Code and/or Logs

Executing pre-compile tasks...
Cannot determine path to 'tools.jar' library for Android API 32 Platform (C:/Users/techn/AppData/Local/Android/Sdk)
Executing post-compile tasks...
Synchronizing output directories...
12/20/2021 2:35 AM - Build completed with 1 error and 0 warnings in 103 ms

**Comment by jahirfiquitiva** [comment]
This is not related to the dashboard. Your android studio and sdk installation is missing some packages

**Comment by jahirfiquitiva** [comment]
👋  We use the issue tracker exclusively for bug reports and feature requests. However, this issue appears to be a support request. Please join the [Dashboards Support Discord Server](https://discordapp.com/invite/78h7xgj) to get help with the project.
