### ISSUE TITLE
Strange bug with the fast scroller

### ISSUE THREAD

**Issue by krux3r** [jahirfiquitiva/Blueprint#30]
Hey.

Found a bug with Blueprint.

So, when trying to scroll with the fast scroller, it opens a strange drawer on the left side, and it can't be scrolled anymore.

- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Blueprint.

### Device/dashboard info:
 - Blueprint version: latest, bundled with Cornie icons.
 - Android version: 7.0 Nougat
 - Device Manufacturer: Huawei
 - Device Name: P10 Lite

### Reproduction Steps

1. Tap the fast scroller
2. Try to scroll down
3. Black side drawer will open

### Actual Result

Here's a video of the issue: https://youtu.be/Xm-dwmb4fAE

**Comment by krux3r** [comment]
What info do you need?

Happens on Huawei P10 Lite, stock 7.0.

**Comment by jahirfiquitiva** [comment]
Did you read the comment by welcome bot? You must fill the issue template properly, otherwise the issue will be ignored.

**Comment by krux3r** [comment]
@jahirfiquitiva sorry, I opened the issue from my phone so I didn't see the template. I hope it is good now.

**Comment by jahirfiquitiva** [comment]
@krux3r ... That's better. But you are not using Blueprint in your own app? So, you found the issue on Cornie by @gowski ?

**Comment by krux3r** [comment]
@jahirfiquitiva yes yes, I am just an icon pack user. Sorry if I issued on the wrong place, but I didn't know should I report it to you or @Gowsky.

**Comment by jahirfiquitiva** [comment]
@krux3r  of course you should have reported it to @Gowsky first. Then he would report it to me if needed.

**Comment by krux3r** [comment]
@jahirfiquitiva so, what now? Should I send him an email or something?

**Comment by jahirfiquitiva** [comment]
@krux3r 
I will contact him and close this issue for now. Thanks anyway for the report

**Comment by krux3r** [comment]
@jahirfiquitiva cool bro. Again, sorry for misunderstanding :)
