### ISSUE TITLE
Dashboard does not disclose data being sent to online requests manager

### ISSUE THREAD

**Issue by link6155** [jahirfiquitiva/Blueprint#301]
### Requirements

- [X] I have verified there are no duplicate active or recent bugs, questions, or requests

### Blueprint Version

2.3.0

### Android Version

13.0.0

### Device Manufacturer

Google

### Device Name

Pixel 7 Pro

### What happened?

The dashboard does not inform the user of where their icon requests are being sent. This is a violation of Google Play's [Prominent Disclosure & Consent Requirement](https://notifications.google.com/g/p/APdRdFzbRN8DsliAhxYPn_jTH3ukucBq0bebUS50h7Ec0TJnTKg0ysK4UgmD9FaHgzNIbygAPaIzpLzy04_6aKnRwoX75mX6X4iZVLNQJhpXPom2DRnUFKXEuv9oTscSc23TEYL-knMH5QyIZGXvsmp5eeNVBWZ2erIY0U8D_Pw9NS1j-X1IEVOuqidteD2Lf7OpG4FHs6Osy-GZdQIaHlqYS787yhAc4FBddzhFvAWIH15O-g) policy. The app should disclose that icon requests are sent to a 3rd party service.

### Reproduction Steps

N/A

### Expected behavior

The user should see a prompt informing them that their icon requests are being sent to a 3rd party service. This prompt should be shown either when they go to the Requests tab or after they send an icon requests.

**Comment by jahirfiquitiva** [comment]
Adding the image you shared with me, for reference:
![image](https://user-images.githubusercontent.com/10360816/221089350-50c57f74-bfdf-451f-80c7-7c977e3fbc80.png)

**Comment by jahirfiquitiva** [comment]
@link6155 Do you think this dialog will suffice? Would you suggest a better copy/text for the content in it?

<img width="320" src="https://user-images.githubusercontent.com/10360816/221434780-384fa87d-9e22-4302-90af-166c5d72a871.jpg" />

**Comment by link6155** [comment]
> @link6155 Do you think this dialog will suffice? Would you suggest a better copy/text for the content in it?

I think it'll suffice. I don't know what else to add, maybe disclosing that sent icon requests will include the app's name and activity, but that's pretty obvious considering it is an icon request.

**Comment by jahirfiquitiva** [comment]
@link6155 I think `information about the installed apps` kind of includes the app name and activity, so it'd probably be ok
