### ISSUE TITLE
Free app with in-app purchase for enabling icons usage

### ISSUE THREAD

**Issue by juanillo62gm** [jahirfiquitiva/Blueprint#309]
### Blueprint Version

2.3.7

### Describe the feature

This allows users to experience the product firsthand before making a purchase, driving more downloads and enhancing the overall user experience.

**Comment by jahirfiquitiva** [comment]
Unfortunately, due to the way icon pack works, we cannot enable or disable its functionality. It will always be enabled.
Therefore, while the idea is good, it is impossible to implement
