### ISSUE TITLE
Iconback (Background) for unthemed icons issue

### ISSUE THREAD

**Issue by thewaliii** [jahirfiquitiva/Blueprint#322]
### Requirements

- [X] I have verified there are no duplicate active or recent bugs, questions, or requests

### Blueprint Version

2.4.2

### Android Version

14

### Device Manufacturer

Nothing, Samsung

### Device Name

S22 Ultra, Nothing 2

### What happened?

I wanted to implement backgrounds (iconback) for unthemed icons. I attempted to do this in my current project, but I encountered a strange issue with some launchers like Microsoft Launcher, Nothing Launcher, where the background gets scaled up or zoomed in and goes outside the icon borders:

![image](https://github.com/user-attachments/assets/fa60bbb7-a33e-4768-a231-129c48ecaf9b)

This is my "iconback" sample:

![image](https://github.com/user-attachments/assets/d73c1bc3-054f-448b-bb53-e0f9c5f5bab5)

I tried everything without success, so I thought there might be an issue with my project. I decided to set up a new project from scratch. In the new project, I only added one line of code in the appfilter.xml file in both locations: 

`<iconback img1="iconback"/>`

However, I encountered the same exact problem, even in this clean project. It works well in Nova Launcher, and when I tried the masking feature, it functioned correctly as well...

![image](https://github.com/user-attachments/assets/57335847-b141-439d-9ebf-4c659cceefa3)

The problem arises in other launchers, where iconback appears blown up; it's strange and seems to be scaled up or zoomed in.

![image](https://github.com/user-attachments/assets/334a25af-3768-4795-af6d-2dbe7dd93faa)

I checked other icon packs on the Play Store that also use blueprint, and they work perfectly without scaling issues.

I must be missing something - perhaps a piece of code or something!

### Reproduction Steps

- Add this line to appfilter.xml + the PNG in the drawable folder.
`<iconback img1="iconback"/>`

![image](https://github.com/user-attachments/assets/a38681e0-36c4-416c-bd49-c64cc2693862)
![image](https://github.com/user-attachments/assets/35c01c7c-c977-4898-9c52-f7ca79651ee7)

- Apply the icon pack in one of these launchers:
MS Launcher., Nothing Launcher. There might be more launchers with the same issue but I didn't try all of them.

### Expected behavior

The background should fit inside the icon boundaries and not go beyond or get scaled like this:

![image](https://github.com/user-attachments/assets/0c324d29-7a8f-41e3-92a1-26b6bb2b1c6b)

### Screenshots or videos

![iconback](https://github.com/user-attachments/assets/14f4a2fc-9dcb-4e7e-b2ca-0c4e5928972d)

**Comment by jahirfiquitiva** [comment]
Unfortunately this is not related to the dashboard and it's only related to the configuration and how each launcher reads it.

Please feel free to ask for help on the random channel of the discord server
