### ISSUE TITLE
Apply 'S Launcher' broken link

### ISSUE THREAD

**Issue by RandleP** [jahirfiquitiva/Blueprint#33]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Blueprint.

### Device/dashboard info:
 - Blueprint version: `1.1.2`
 - Android version: `7.0`
 - Device Manufacturer: `Samsung`
 - Device Name: `Galaxy S7`

```kotlin
When pressing S Launcher in the Apply section the link to the PlayStore is broken.

Feature request: launchers.xml like IconShowcase to remove launchers
```

### Reproduction Steps

1. 
2. 
3.

**Comment by jahirfiquitiva** [comment]
Please open a new issue for the feature request
