### ISSUE TITLE
Renaming FAB 'no selected apps'

### ISSUE THREAD

**Issue by RandleP** [jahirfiquitiva/Blueprint#36]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Blueprint.

### Device/dashboard info:
 - Blueprint version: `1.1.2`
 - Android version: `7.0`
 - Device Manufacturer: `Samsung`
 - Device Name: `Galaxy S7`

No selected apps dialog screen is shown in the Icon Request section. The current text reads as follows: "... Select some before pressing the FAB again." I think 99% of the users won't uinderstand the meaning of FAB (FloatingActionButton). Perhaps something like: "Select some before sending your icon request"

### Reproduction Steps

1. Select no apps and press send in icon request
2. 
3. 

### Actual Result

![screenshot_20180224-122122](https://user-images.githubusercontent.com/11807779/36629910-6f417948-195d-11e8-8da1-d12d889e5864.png)

**Comment by jahirfiquitiva** [comment]
Please add reproductions steps and screenshots

**Comment by RandleP** [comment]
Done :)
