### ISSUE TITLE
"Enable notifications" in settings when not used

### ISSUE THREAD

**Issue by RandleP** [jahirfiquitiva/Blueprint#37]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Blueprint.

### Device/dashboard info:
 - Blueprint version: `1.1.2`
 - Android version: `7.0`
 - Device Manufacturer: `Samsung`
 - Device Name: `Galaxy S7`

If notifications are not used at all, it still shows the option for the user to 'Enable Notifications' in Settings menu. 

### Reproduction Steps

1. 
2. 
3.

**Comment by jahirfiquitiva** [comment]
There's no proper way for me to know whether you enabled the notifications or not. So I will keep it like that.

The end user would simply think you never send notifications and that'd be it 🤷🏻‍♂️
