### ISSUE TITLE
Changelog: see new icons

### ISSUE THREAD

**Issue by RandleP** [jahirfiquitiva/Blueprint#38]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Blueprint.

### Device/dashboard info:
 - Blueprint version: `1.1.2`
 - Android version: `7.0`
 - Device Manufacturer: `Samsung`
 - Device Name: `Galaxy S7`

This feature was added in ISc: a link in the changelog (check latest icons or something like that) that directly shows the latest icons

**Comment by jahirfiquitiva** [comment]
Sorry, but I won't make this happen.
