### ISSUE TITLE
Taking some time to load all of icons

### ISSUE THREAD

**Issue by chocomilk-dev** [jahirfiquitiva/Blueprint#43]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Blueprint.

### Device/dashboard info:
 - Blueprint version: `1.1.3`
 - Android version: `8.1`
 - Device Manufacturer: `Essential Products`
 - Device Name: `Essential (PH-1)`

### Reproduction Steps

1. Updated Blueprint library to 1.1.3 by editing build.gradle
2. Translated to Korean by creating values.xml at Blueprint, Kuper, and Frames library project
3. Did not show the changelog when I first opened the app and didn't show a number of icons during a minute.
4. Downloaded latest source from GitHub and repeated second course.
5. Same thing happened.
6. Cleaned gradle cache and ran my app. (Repeated, actually)
7. Generated signed app.
8. Users complained there's only 44 icons, Although there's much more. (And the app which I ran had  the exact amount of them)
9. Cleaned gradle cache, build file and gradle file.
10. Ran the app *without creating translation file*.

### Expected Result
Working without bug

### Actual Result
Changelog appeared, but took a minute to load all of icons.

In fact, wallpapers weren't shown when I repeated 6 course twice
so I tried to fix Frames' json string, `<string name="json_url"/>`
Then, It worked!
I think overriding is not working properly.

![image](https://user-images.githubusercontent.com/26513366/36642078-3a5d07f8-1a7d-11e8-9037-0f607910f73b.png)
Screenshot from user's app.
![image](https://user-images.githubusercontent.com/26513366/36642081-52da4d18-1a7d-11e8-818c-1b395328d8bc.png)
Screenshot from mine.

**Comment by jahirfiquitiva** [comment]
There are too many issues mentioned in this one. Also "Working without bug" is a pretty vague description of an expected result. Of course everyone wants that.

Please create simpler and more specific issues and be more clear on what you want and what is happening.
