### ISSUE TITLE
Number of icons number taking too long to load

### ISSUE THREAD

**Issue by Gowsky** [jahirfiquitiva/Blueprint#47]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Blueprint.

### Device/dashboard info:
 - Blueprint version: `1.1.3`
 - Android version: `Any version`
 - Device Manufacturer: `Any device`

### Reproduction Steps

1. Open the app that includes large amount of icons e.g. 5000

### Expected Result
App saves the amount of icons and their list, so it doesn't have to load them with every app launch.
The app could cache and associate them with app's version code/name, so if it's the same, it would just load cached values instead of reloading them.

### Actual Result
App loads the amount of icons and their list with every app launch. With large amount of icons it takes over 12 seconds (on my device) to load over 5000 icons.

**Comment by jahirfiquitiva** [comment]
Closing this in favor of version `1.1.4` _(Available soon ™)_
