### ISSUE TITLE
Big icons and preview not displaying properly on tablets

### ISSUE THREAD

**Issue by kushjain94** [jahirfiquitiva/Blueprint#53]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Blueprint.

### Device/dashboard info:
 - Blueprint version: `1.1.3`
 - Android version: `6.0`
 - Device Manufacturer: `Samsung`
 - Device Name: `Tab S (T805)`

"Icons are too large and there is no option to scale the size of icons. The issue is also with other icon packs based on blueprint, one such is dux_icon pack. This was not the case with older dashboard-Iconshowcase."
![screenshot_2018-03-22-09-24-13](https://user-images.githubusercontent.com/35252842/37751132-a2e6f206-2db6-11e8-8efe-24d4d744fe2c.png)
![screenshot_2018-03-22-09-23-39](https://user-images.githubusercontent.com/35252842/37751137-b04dc848-2db6-11e8-92d6-293f74c35257.png)

**Comment by kushjain94** [comment]
I have now added the detail and screenshots

**Comment by jahirfiquitiva** [comment]
Closing this in favor of version `1.1.4` _(Available soon ™)_
