### ISSUE TITLE
Please update FAQs to be include bottom navigation

### ISSUE THREAD

**Issue by kushjain94** [jahirfiquitiva/Blueprint#54]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Blueprint.

### Device/dashboard info:
 - Blueprint version: `?`
 - Android version: `?`
 - Device Manufacturer: `?`
 - Device Name: `?`

```kotlin
println("Hello, world!")
```

```Gradle
java.lang.RuntimeException: This is an example Exception log
    at jahirfiquitiva.libs.blueprint.HelloWorld
    at jahirfiquitiva.libs.blueprint.HelloWorld$ThisIsNotARealLog
    at android.app.Instrumentation.callActivityOnResume(Instrumentation.kt)
```

### Reproduction Steps

1. 
2. 
3.

**Comment by lumiqcreative** [comment]
The FAQ text will soon be updated to match all features and possible configurations of the dashboard.

**Comment by jahirfiquitiva** [comment]
@lumiqcreative [Here](https://github.com/jahirfiquitiva/Blueprint/blob/master/library/src/main/res/values/translatable_strings.xml#L110)

**Comment by jahirfiquitiva** [comment]
@lumiqcreative Sorry for bothering, have you made any progress on this :sweat_smile: ?

**Comment by lumiqcreative** [comment]
@jahirfiquitiva Oops, I've forgotten. I'll get to work in the upcoming days.

**Comment by jahirfiquitiva** [comment]
Closing this in favor of version `1.1.4` _(Available soon ™)_
