### ISSUE TITLE
Adaptive icons support?

### ISSUE THREAD

**Issue by JustMeErazem** [jahirfiquitiva/Blueprint#55]
Does the dashboard support adaptive icons introduced in Android Oreo?

**Comment by Gowsky** [comment]
What do you mean exactly? Support for adaptive icons as an app icon, or as adaptive icons pack?

**Comment by JustMeErazem** [comment]
As an adaptive icon pack. For example: You create a foreground with the actual icon and shadow, and provide multiple backgrounds (square, circle, ...). Then the user can select the shape in their launcher and the icons automatically change according to that.

**Comment by Gowsky** [comment]
No, it's not. AFAIK The only launcher that supports adaptive icon packs is Action Launcher and its API isn't publicly available.

**Comment by JustMeErazem** [comment]
@Gowsky under Wiki -> Changing splash...

There is something about adding Adaptive icons, so does that mean I can atleast change the app icon?

**Comment by Gowsky** [comment]
Yes, you can. Using adaptive icon as your launcher icon is very simple.

**Comment by JustMeErazem** [comment]
Thanks
