### ISSUE TITLE
Suggestion to change icon animations

### ISSUE THREAD

**Issue by myfrom** [jahirfiquitiva/Blueprint#57]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

- [x] I have verified that I am using the latest version of Blueprint.

### Device/dashboard info:

- Blueprint version: `1.1.3`

- Android version: `7.1`

- Device Manufacturer: `OnePlus`

- Device Name: `3T`

### Reproduction Steps

1. Open the dashboard app

2. Make sure animations are turned on in settings

3. _Case 1_ Switch to icons page and click on any of the icons, notice the animation

4. _Case 2_ Switch to main page click on showcased icons on main page, notice the animation

[Video](https://youtu.be/IBa93dCErPU)

### Explanation

Motion should be meaningful and guide users through the app. Current animations aren't best at achieving those goals.

Especially the animation in icons tab look like the icon is appearing out of nowhere, just growing in a dialog that popped-up. This animation is can also get quite boring when you browse many icons. I'd suggest to change it to an arc animation, just like in the Play Store - clicked icon would move to the center of the screen on an arc path and meanwhile a dialog would appear behind it. That way it would also show users where the icon was so they can continue browsing from that point. And it would be way more contextual, the icon no longer would hide and show out of nowhere but be taken from a specific place and would return there.

The second animation, the one on the main page lacks exit animation. The icons just disappear and new ones grow on their place. I think a better way would be to fade-out and transition up existing icons and make the new ones enter from bottom of the showcase section and fade-in.  

-------

I'm not saying that the current animations are bad, I appreciate the time and effort that was put to this dashboard. I just wanted to suggest a way to make it even better :wink:

**Comment by myfrom** [comment]
Are we gonna leave it _stale_ or can we stop that process?

**Comment by jahirfiquitiva** [comment]
So, after giving it a deep thought, I will be closing this.
I know it would be nice to implement the animations you mention. That's a fact.

Anyway, currently android does not support the kind of animation you would expect. To achieve it, I'd have to implement a whole different UI for the icon preview, which I consider needless, given the icon preview does not (and will not) provide any real features besides showing the icon name.

About the second animation, I think it's good as it is and I won't change it.

Thanks for your suggestions, though. If you want to, feel free to work on them and implement them. Create a Pull Request, and I will be sure to merge it and credit you in the app.
