### ISSUE TITLE
Translation error found on Simplified Chinese

### ISSUE THREAD

**Issue by antoniacrespoa2** [jahirfiquitiva/Blueprint#59]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Blueprint.

### Device/dashboard info:
 - Blueprint version: `1.1.3`
 - Android version: `6.0.1`
 - Device Manufacturer: `Motorola`
 - Device Name: `Moto X 1st Gen`

### Expected Result
The last radio option in the dialog should be "浅色与Amoled主题自动切换", "Amoled" not "Almoled".
Just a spelling mistake but I didn't find the word in Blueprint's translation project page.

And, more translation strings are needed, since there are still a lot of untranslated things.

### Actual Result
![alt text](https://raw.githubusercontent.com/antoniacrespoa2/meeye_iconpack_play_store_code/master/app/src/main/res/Screenshot_20180411-161434.png)

**Comment by jahirfiquitiva** [comment]
Hi @antoniacrespoa2 

Thanks for your feedback ... If you're willing to, please contribute to the project by fixing these spelling mistakes on the translations site. After they are fixed, they will be added to the project and everything will be correct. 😄 

[This is the website for translations](http://j.mp/BlueprintTranslations)

Thanks

**Comment by antoniacrespoa2** [comment]
Thanks, but I know it, the Simplified Chinese translation was completed by me.
I mean I didn't find the phrase in the Blueprint translation site, is there reasons of it or what can I do?

**Comment by jahirfiquitiva** [comment]
@antoniacrespoa2 

You can try to translate [Frames](http://j.mp/FramesTranslations) and/or [Kuper](http://j.mp/KuperTranslations) ... One of them will have the phrases
