### ISSUE TITLE
Suggestion to choose between multiple icon variations

### ISSUE THREAD

**Issue by alexbracken** [jahirfiquitiva/Blueprint#61]
Hi, I'm the developer of Kecil for Android.

In our icon pack, there are multiple variations of each icon. For example, there is one with a dark background, one with a light background, and one with no background. 

For ease of use, it would be helpful for users to be able to pick what variation they want to apply. Whether this means users choosing which appfilter.xml to apply from, or having multiple selection activities, I believe this capability would allow some customization and flexibility for icon packs that has never been seen before. If there is a way to do this as the dashboard is as of now, please let me know. Otherwise, I think this would be an interesting feature to add.

**Comment by Gowsky** [comment]
This feature requires Launcher support. 
Appfilter.xml, as other xml files can't be modified at runtime and there can't be multiple versions of it.

It could work if launchers supported reading appfilter from outside the app e.g. from internal storage. In this case, we would be able to dynamically edit appfilter. 
But they don't, and the dashboard alone can't add features like this.
