### ISSUE TITLE
Issue with MainActivity when building 

### ISSUE THREAD

**Issue by ChildishGiant** [jahirfiquitiva/Blueprint#64]
I'm assuming this is all user error but when I build, I get thrown this error: 
`Error:(28, 1) Class 'MainActivity' is not abstract and does not implement abstract base class member public abstract fun getLicKey(): String? defined in jahirfiquitiva.libs.blueprint.ui.activities.BottomNavigationBlueprintActivity`

And that's from this section of code:

```
package com.childishgiant.inset

import com.github.javiersantos.piracychecker.PiracyChecker
import com.childishgiant.inset.BuildConfig
import jahirfiquitiva.libs.blueprint.data.models.NavigationItem
import jahirfiquitiva.libs.blueprint.ui.activities.BottomNavigationBlueprintActivity

class MainActivity : BottomNavigationBlueprintActivity() {
```

I followed the [wiki on fixing a wrong import](https://github.com/jahirfiquitiva/Blueprint/wiki/Setting-up-your-MainActivity.kt#fixing-wrong-import) but am still getting this. I'm assuming I need to change the 3rd and 4th imports but I can't figure out what to.

**Comment by jahirfiquitiva** [comment]
Don't remove anything from the code in `MainActivity.kt` ... You can change, but don't remove

**Comment by ChildishGiant** [comment]
![image](https://user-images.githubusercontent.com/13716824/39408459-6eb814b6-4bce-11e8-9a90-98b1d82b57fa.png)

What does one do while you are devving and don't have a license key?

**Comment by Gowsky** [comment]
Just leave it as it is.

**Comment by ChildishGiant** [comment]
Thanks 😄 The `Default one isn't valid and could cause issues in your app.` threw me off
