### ISSUE TITLE
When landscape, the showcase apps get cut off

### ISSUE THREAD

**Issue by ChildishGiant** [jahirfiquitiva/Blueprint#67]

**Comment by ChildishGiant** [comment]
![screenshot_20180502-182224](https://user-images.githubusercontent.com/13716824/39538963-565bf38c-4e36-11e8-8f44-6a3a3c4b7a16.jpg)
Sorry for the immediate lack of info but I was opening this from my phone.

**Comment by jahirfiquitiva** [comment]
@ChildishGiant Already [reported here](https://github.com/jahirfiquitiva/Blueprint/issues/53)
