### ISSUE TITLE
Action Bar displays 3-dot menu icon instead of help icon after exiting search in Help screen

### ISSUE THREAD

**Issue by SanchithHegde** [jahirfiquitiva/Blueprint#72]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Blueprint.

### Device/dashboard info:
 - Blueprint version: `1.1.4`
 - Android version: `8.1`
 - Device Manufacturer: `Motorola`
 - Device Name: `Moto G3 (2015)`

### Reproduction Steps
1. Open Help screen by tapping on 3-dot menu icon in the action bar and then tapping on "Help".
2. The Help screen is displayed. Notice the action bar displayed. *(Screenshot 1)*
3. Tap on the Search icon. An input field to enter search term is displayed. *(Screenshot 2)*
4. Tap on Back icon. Action bar with a 3-dot menu icon instead of the Help (chat bubbles) icon is displayed. *(Screenshot 3)*

### Expected Result
Action bar displays Help (chat bubbles) icon after exiting search.

### Actual Result
Action bar displays displays 3-dot menu icon (which does nothing on tap) instead of Help (chat bubbles) icon after exiting search. 

### Screenshots
|  ![Screenshot 1](https://user-images.githubusercontent.com/22217505/39758899-d0d52914-52ee-11e8-8fad-2304e5e40954.png "Screenshot 1")  |  ![Screenshot 2](https://user-images.githubusercontent.com/22217505/39758901-d111f92a-52ee-11e8-8db6-3ebe0986cb77.png "Screenshot 2")  |  ![Screenshot 3](https://user-images.githubusercontent.com/22217505/39758902-d14b329e-52ee-11e8-9b47-38f47741ca3d.png "Screenshot 3")  |
| :-------: | :-------: | :-------: |
| Screenshot 1 | Screenshot 2 | Screenshot 3 |

*Screenshots from the Blueprint sample app, cropped to show required part only*

**Comment by jahirfiquitiva** [comment]
Fixed in v `1.1.7`
