### ISSUE TITLE
Difference between the two drawable files

### ISSUE THREAD

**Issue by BastienMottier** [jahirfiquitiva/Blueprint#73]
Hello, in the wiki, you mentioned than there is no difference between the drawable.

But I noticed a little difference : 
xml/drawable.xml => The icons are ordonned by categories. You can filter them in the dashboard. This one are only used by the dashboard. 
assets/drawable.xml => used by the launcher when you pick an icon (tested with OnePlus Launcher and lawnchair). If you use the same (with categories), your icons appear multiple time in the icon picker. 

So, I think you can edit the wiki to mention that.

**Comment by Gowsky** [comment]
Actually there's no difference in these 2 drawable.xml files, however as you've mentioned - one is used by Blueprint and one by launcher.You can keep both of these files exactly the same.

Lawnchair Launcher generates "All icons" tab automatically, so if you have some icons in 2 tabs e.g. "Latest" and "Apps", they will appear twice in it. In addition, (I guess) if you have "All icons" tab in your drawable.xml file, Lawnchair will generate such tab either way, so all icons may appear twice or more.

Thanks for the tip, I'll mention it in the wiki.
