### ISSUE TITLE
Changing sections order breaks icons filters and search functionalities

### ISSUE THREAD

**Issue by zwylde** [jahirfiquitiva/Blueprint#77]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Blueprint.

### Device/dashboard info:
 - Blueprint version: `1.1.5`
 - Android version: `8.0`
 - Device Manufacturer: `Samsung`
 - Device Name: `S8

**Comment by jahirfiquitiva** [comment]
Fixed in v `1.1.6`
