### ISSUE TITLE
Status bar color changes based on background

### ISSUE THREAD

**Issue by sreeragag7** [jahirfiquitiva/Blueprint#96]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version.

### Device/App info:
 - Blueprint Version: `1.2.1`
 - Android version: `8.1`
 - Device Manufacturer: `Oneplus`
 - Device Name: `3T`

### Describe the bug
The status bar changes depending on the background color and not the accent color. 

### Reproduction Steps
1. Updated to latest version of Blueprint (1.2.1)
2. Status bar color is dependent on background color

### Expected behavior

Status bar color should change based on accent color

### Screenshots

![photo_2018-06-05_21-01-03](https://user-images.githubusercontent.com/25480372/40986333-9305fe44-6903-11e8-98c9-2da3dd163724.jpg)

**Comment by jahirfiquitiva** [comment]
> Status bar color is dependent on background color

Have you checked the code? Or is it just an assumption?

If you checked the code, please link me to the exact line where this is occurring so I can solve the issue faster 😀

**Comment by sreeragag7** [comment]
I just  changed the value for light_theme_background in colors.xml to confirm, and yes it changed the status bar color along with the background.
